import { AiFillStar } from "react-icons/ai";
import hockey from "./hockey.webp";

const data = [
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/hockey_kevin_rodrigues_firework_85_skateboard_deck.webp?v=1709204886",
    "title": "Hockey Rodriguess Firework 8.5 deck",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 100,
    "company": "Hockey",
    "color": "black",
    "category": "sneakers",
    "size": "8.5",
    "year": 2021
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/sk8mafia-marshall-heath-geo-skateboard-deck-8125_540x.jpg?v=1679840455",
    "title": "SKATEMAFIA HEATH GEO 8.125 DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 110,
    "company": "Sk8mafia",
    "color": "red",
    "category": "sneakers",
    "size": "8.125",
    "year": 2022
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/polar_jamie_platt_caged_825_skateboard_deck_540x.webp?v=1710521085",
    "title": "POLAR SKATE CO. PLATT CAGED 8.25 DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 110,
    "company": "Polar",
    "color": "green",
    "category": "sneakers",
    "size": "8.25",
    "year": 2023
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/polar_jamie_platt_apple_85_skateboard_deck_540x.webp?v=1710509452",
    "title": "POLAR SKATE CO. PLATT APPLE 8.5 DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 200,
    "company": "Polar",
    "color": "white",
    "category": "sneakers",
    "size": "8.5",
    "year": 2021
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/hockey_plaid_gold_skateboard_deck_59b09c1f-9b3a-46d4-a074-942ad57c1658.webp?v=1709204875",
    "title": "HOCKEY PLAID GOLD 9.0 DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 250,
    "company": "Hockey",
    "color": "gold",
    "category": "flats",
    "size": "9.0",
    " year": 2022
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/polar_skate_co_jamie_platt_angel_85_skateboard_deck_top_and_bottom_540x.webp?v=1696688964",
    "title": "POLAR SKATE CO. PLATT ANGEL 8.5 P2 SHAPE DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 250,
    "company": "Polar",
    "color": "Multi",
    "category": "flats",
    "size": "8.5",
    "year": 2023
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/sk8mafia_stephen_lawyer_smug_81_skateboard_deck_540x.webp?v=1708779542",
    "title": "SK8MAFIA LAWYER SMUG 8,125 DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 100,
    "company": "Sk8mafia",
    "color": "white",
    "category": "flats",
    "size": "8.125",
    "year": 2021
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/zero-zero-burman-end-of-time-85-deck-handelsware-611816_540x.webp?v=1710399207",
    "title": "ZERO BURMAN END OF TIME 8.5 DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 110,
    "company": "Zero",
    "color": "green",
    "category": "sneakers",
    "size": "8.5",
    "year": 2022
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/polar_dane_brady_pigeons_85_skateboard_deck_bottom_540x.webp?v=1710509449",
    "title": "POLAR SKATE CO. BRADY PIGEONS 8.5 DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 240,
    "company": "Polar",
    "color": "blue",
    "category": "sneakers",
    "size": "8.5",
    "year": 2023
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/alien-workshop-alien-workshop-spectrum-775-deck-white-985680_540x.jpg?v=1710399638",
    "title": "ALIEN WORKSHOP SPECTRUM 8.0 DECK WHITE",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 150,
    "company": "Alien Workshop",
    "color": "white",
    "category": "sneakers",
    "size": "8.0",
    "year": 2021,
    "description": "Spectrum — это доска для скейтборда от Alien Workshop Ширина 7,75 дюйма, длина 31,5 дюйма, колесная база 14,0 дюйма. Деки для скейтбордов Alien имеют немного более крутую вогнутость или изгиб носа и хвоста и полные формы с более широким носом и хвостом для большего контроля. Сделано в Мексике. Дека из 7 слоев канадского клена с экологически чистым клеем на водной основе."
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/polar_aaron_herrington_return_soon_825_skateboard_deck_540x.webp?v=1710509315",
    "title": "POLAR SKATE CO. HERRINGTON RETURN SOON 8.25 DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 150,
    "company": "Polar",
    "color": "white",
    "category": "sneakers",
    "size": "8.25",
    "year": 2021
  },
  {
    "img": "https://freedomskateshop.at/cdn/shop/products/sk8mafia_tyler_surrey_smug_825_skateboard_deck_540x.webp?v=1708779419",
    "title": "SK8MAFIA SURREY SMUG 8.25 DECK",
    "star": "star",
    "reviews": "(123 reviews)",
    "prevPrice": 140.00,
    "newPrice": 150,
    "company": "Sk8mafia",
    "color": "green",
    "category": "sneakers",
    "size": "8.25",
    "year": 2022
  },
  // {
  //   img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
  //   title: "Roma Basic Sneaker",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Puma",
  //   color: "white",
  //   category: "sneakers",
  //   size: "8.25",
  //   year: "2023",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
  //   title: "Pacer Future Doubleknit",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Puma",
  //   color: "black",
  //   category: "sneakers",
  //   size: "8.25",
  // },

  // {
  //   img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
  //   title: "Fusion Evo Golf Shoe",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "Puma",
  //   color: "green",
  //   category: "sneakers",
  //   size: "8.25",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
  //   title: "Rainbow Chex Skate",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "Vans",
  //   color: "red",
  //   category: "flats",
  //   size: "8.0",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
  //   title: "Low-Top Trainers",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "Vans",
  //   color: "white",
  //   category: "sandals",
  //   size: "9.0",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
  //   title: "Vans Unisex Low-Top",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "Vans",
  //   color: "blue",
  //   category: "sandals",
  //   size: "9.0",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
  //   title: "Classic Bandana Sneakers",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Nike",
  //   color: "black",
  //   category: "sandals",
  //   size: "8.0",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
  //   title: "Chunky High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Vans",
  //   color: "black",
  //   category: "heels",
  //   size: "8.5",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
  //   title: "Slip On Stiletto High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "100",
  //   company: "puma",
  //   color: "black",
  //   category: "heels",
  //   size: "8.125",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
  //   title: "DREAM PAIRS Court Shoes",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Nike",
  //   color: "red",
  //   category: "heels",
  //   size: "8.125",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
  //   title: "Nike Air Vapormax Plus",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "200",
  //   company: "Nike",
  //   color: "red",
  //   category: "sneakers",
  //   size: "8.0",
  // },

  // {
  //   img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
  //   title: "Low Mid Block Heels",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "200",
  //   company: "Nike",
  //   color: "black",
  //   category: "heels",
  //   size: "8.0",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
  //   title: "Chunky High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  //   size: "8.0",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
  //   title: "Amore Fashion Stilettos",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Adidas",
  //   color: "white",
  //   category: "heels",
  //   size: "8.0",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
  //   title: "Bridal Sandals Glitter",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  //   size: "8.125",
  // },
  // {
  //   img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
  //   title: "Wedding Prom Bridal",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "flats",
  //   size: "8.5",
  // },
];

export default data;
